<?
session_start();
session_register("loginUname");
session_register("loginUid");
session_register("loginDesignation");
session_register("loginProject");
session_register("loginFullName");
session_register("loginProjectName");
?>